LOG_LEVEL = 20
SYMBOL = 'XBTUSD'
BASE_URL = 'https://www.bitmex.com/api/v1/'
API_KEY = 'KKS6KLVlrYCMh1kqFZcX6QNI'
API_SECRET = 'buUdaDtZ8cm2s-RyeXq2wLxuRIpsH7Uy_CRF74XTUBG-Nzxr'
ORDER_ID_PREFIX = ''
POST_ONLY = ''
TIMEOUT = ''
API_REST_INTERVAL = ''
API_ERROR_INTERVAL = ''
# settings = dict()
